# Generated by Django 3.2.7 on 2021-10-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('contents', models.CharField(max_length=600)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('positif', models.PositiveIntegerField()),
                ('negatif', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('contents', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('positif', models.PositiveIntegerField()),
                ('negatif', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.article')),
            ],
        ),
    ]
