# Generated by Django 3.2.7 on 2021-10-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='negatif',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='positif',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='negatif',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='positif',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
